# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Libro de Urología Pediátrica
email: admin@pediatricurologybook.com
tagline: Un libro en línea gratuito de urología pediátrica
description: >- # this means to ignore newlines until "baseurl:"
  Este libro en línea gratuito de Urología Pediátrica, Edición 1.0, presenta temas que se actualizan con frecuencia, como el manejo de la hidronefrosis, técnicas de hipospadias, enfoques para la infección del tracto urinario, información sobre disfunción del intestino y la vejiga, vejiga neurogénica, oncología urológica pediátrica y mucho más.
baseurl: "/es" # the subpath of your site, e.g. /blog
url: "https://pediatricurologybook.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pediatricurologybook
github_username:  kylerove

# polyglot settings
languages: ["es"]
default_lang: "es"
exclude_from_localization: ["_config.yml", "assets", "_layouts", "_includes", "vendor"]
parallel_localization: true
version: 1.0.0
encoding: utf-8
permalink: pretty

# Build settings
theme: null
plugins:
  - jekyll-seo-tag
  - jekyll-toc
  - jekyll-polyglot
  
collections:
  chapters:
    output: true
    sections: true
    sort_by: sort_key
    permalink: /libro/capitulo/:title.html
    
kramdown:
  auto_ids          : true
  entity_output     : as_char
  toc_levels        : [1, 2, 3, 4, 5, 6]
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
